name: notify-stale-release
on:
    workflow_dispatch:
        branches:
            - main
    schedule:
        - cron: "30 21 * * 1-5"
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Check if there's a release pending
              id: notify
              uses: phorest/github-stale-release-notifier@v1.0.2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  stale-days: 1
                  slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
